name: Deploy Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy Function
        # The --workdir flag tells Supabase to look inside your subesnet-main folder
        run: supabase functions deploy diagnostic-stream-tool --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt --workdir subesnet-main
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
